dangerous_permissions_not_to_be_revoked_from_packages = \
	android.permission.READ_CALL_LOG-from-com.google.android.dialer \
	android.permission.WRITE_CALL_LOG-from-com.google.android.dialer \
	android.permission.ANSWER_PHONE_CALLS-from-com.simplemobiletools.contacts.pro \
	android.permission.CALL_PHONE-from-com.simplemobiletools.contacts.pro \
	android.permission.GET_ACCOUNTS-from-com.simplemobiletools.contacts.pro \
	android.permission.READ_CONTACTS-from-com.simplemobiletools.contacts.pro \
	android.permission.READ_PHONE_STATE-from-com.simplemobiletools.contacts.pro \
	android.permission.WRITE_CONTACTS-from-com.simplemobiletools.contacts.pro \
	android.permission.READ_EXTERNAL_STORAGE-from-com.simplemobiletools.filemanager.pro \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.simplemobiletools.filemanager.pro \
	android.permission.READ_EXTERNAL_STORAGE-from-com.simplemobiletools.gallery.pro \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.simplemobiletools.gallery.pro \
	android.permission.CAMERA-from-com.whatsapp \
	android.permission.READ_EXTERNAL_STORAGE-from-com.whatsapp \
	android.permission.RECORD_AUDIO-from-com.whatsapp \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.whatsapp \
	android.permission.ACCESS_FINE_LOCATION-from-net.osmand.plus \
	android.permission.CAMERA-from-net.sourceforge.opencamera \
	android.permission.READ_EXTERNAL_STORAGE-from-net.sourceforge.opencamera \
	android.permission.WRITE_EXTERNAL_STORAGE-from-net.sourceforge.opencamera \
	android.permission.READ_EXTERNAL_STORAGE-from-org.mozilla.fennec_fdroid \
	android.permission.WRITE_EXTERNAL_STORAGE-from-org.mozilla.fennec_fdroid \
	android.permission.READ_CONTACTS-from-org.smssecure.smssecure \
	android.permission.READ_PHONE_STATE-from-org.smssecure.smssecure \
	android.permission.RECEIVE_MMS-from-org.smssecure.smssecure \
	android.permission.RECEIVE_SMS-from-org.smssecure.smssecure \
	android.permission.SEND_SMS-from-org.smssecure.smssecure \
	android.permission.WRITE_CONTACTS-from-org.smssecure.smssecure \
	
