non_revocable_dangerous_permissions_from_packages = \
	android.permission.GET_ACCOUNTS-from-android \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.bluetooth \
	android.permission.GET_ACCOUNTS-from-com.android.bluetooth \
	android.permission.READ_CONTACTS-from-com.android.bluetooth \
	android.permission.WRITE_CONTACTS-from-com.android.bluetooth \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.companiondevicemanager \
	android.permission.ACCESS_FINE_LOCATION-from-com.android.companiondevicemanager \
	android.permission.CALL_PHONE-from-com.android.emergency \
	android.permission.READ_CONTACTS-from-com.android.emergency \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.location.fused \
	android.permission.ACCESS_FINE_LOCATION-from-com.android.location.fused \
	android.permission.READ_CONTACTS-from-com.android.nfc \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.phone \
	android.permission.CALL_PHONE-from-com.android.phone \
	android.permission.GET_ACCOUNTS-from-com.android.phone \
	android.permission.READ_CONTACTS-from-com.android.phone \
	android.permission.RECORD_AUDIO-from-com.android.phone \
	android.permission.USE_SIP-from-com.android.phone \
	android.permission.WRITE_CONTACTS-from-com.android.phone \
	com.android.voicemail.permission.ADD_VOICEMAIL-from-com.android.phone \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.printspooler \
	android.permission.ACCESS_FINE_LOCATION-from-com.android.printspooler \
	android.permission.READ_CALENDAR-from-com.android.providers.calendar \
	android.permission.WRITE_CALENDAR-from-com.android.providers.calendar \
	android.permission.GET_ACCOUNTS-from-com.android.providers.contacts \
	android.permission.READ_CONTACTS-from-com.android.providers.contacts \
	android.permission.READ_PHONE_STATE-from-com.android.providers.contacts \
	android.permission.WRITE_CONTACTS-from-com.android.providers.contacts \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.settings \
	android.permission.ACCESS_FINE_LOCATION-from-com.android.settings \
	android.permission.CALL_PHONE-from-com.android.settings \
	android.permission.CAMERA-from-com.android.settings \
	android.permission.READ_CONTACTS-from-com.android.settings \
	android.permission.READ_PHONE_STATE-from-com.android.settings \
	android.permission.WRITE_CONTACTS-from-com.android.settings \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.shell \
	android.permission.ACCESS_FINE_LOCATION-from-com.android.shell \
	android.permission.CALL_PHONE-from-com.android.shell \
	android.permission.GET_ACCOUNTS-from-com.android.shell \
	android.permission.READ_CALENDAR-from-com.android.shell \
	android.permission.READ_CONTACTS-from-com.android.shell \
	android.permission.READ_PHONE_STATE-from-com.android.shell \
	android.permission.WRITE_CALENDAR-from-com.android.shell \
	android.permission.WRITE_CONTACTS-from-com.android.shell \
	android.permission.ACCESS_COARSE_LOCATION-from-com.android.systemui \
	android.permission.CAMERA-from-com.android.systemui \
	android.permission.GET_ACCOUNTS-from-com.android.systemui \
	android.permission.READ_CONTACTS-from-com.android.systemui \
	android.permission.READ_PHONE_STATE-from-com.android.systemui \
	android.permission.RECORD_AUDIO-from-com.android.systemui \
	android.permission.ACCESS_MEDIA_LOCATION-from-com.android.vending \
	android.permission.ACCESS_COARSE_LOCATION-from-com.google.android.gms \
	android.permission.ACCESS_FINE_LOCATION-from-com.google.android.gms \
	android.permission.ACTIVITY_RECOGNITION-from-com.google.android.gms \
	android.permission.CAMERA-from-org.codeaurora.ims \
	android.permission.READ_PHONE_STATE-from-org.codeaurora.ims \
	
