dangerous_permissions_not_to_be_revoked_from_packages = \
	android.permission.READ_EXTERNAL_STORAGE-from-ch.protonmail.android \
	android.permission.WRITE_EXTERNAL_STORAGE-from-ch.protonmail.android \
	android.permission.READ_CONTACTS-from-com.fsck.k9 \
	android.permission.READ_EXTERNAL_STORAGE-from-com.fsck.k9 \
	android.permission.WRITE_CONTACTS-from-com.fsck.k9 \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.fsck.k9 \
	android.permission.CALL_PHONE-from-com.google.android.contacts \
	android.permission.GET_ACCOUNTS-from-com.google.android.contacts \
	android.permission.READ_CONTACTS-from-com.google.android.contacts \
	android.permission.READ_PHONE_STATE-from-com.google.android.contacts \
	android.permission.WRITE_CONTACTS-from-com.google.android.contacts \
	android.permission.CALL_PHONE-from-com.google.android.dialer \
	android.permission.READ_CALL_LOG-from-com.google.android.dialer \
	android.permission.READ_CONTACTS-from-com.google.android.dialer \
	android.permission.READ_PHONE_STATE-from-com.google.android.dialer \
	android.permission.WRITE_CALL_LOG-from-com.google.android.dialer \
	android.permission.READ_EXTERNAL_STORAGE-from-com.simplemobiletools.filemanager.pro \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.simplemobiletools.filemanager.pro \
	android.permission.READ_EXTERNAL_STORAGE-from-com.simplemobiletools.gallery.pro \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.simplemobiletools.gallery.pro \
	android.permission.CAMERA-from-com.whatsapp \
	android.permission.READ_EXTERNAL_STORAGE-from-com.whatsapp \
	android.permission.RECORD_AUDIO-from-com.whatsapp \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.whatsapp \
	android.permission.ACCESS_FINE_LOCATION-from-net.osmand.plus \
	android.permission.CAMERA-from-net.sourceforge.opencamera \
	android.permission.READ_EXTERNAL_STORAGE-from-net.sourceforge.opencamera \
	android.permission.WRITE_EXTERNAL_STORAGE-from-net.sourceforge.opencamera \
	android.permission.READ_EXTERNAL_STORAGE-from-org.mozilla.fennec_fdroid \
	android.permission.WRITE_EXTERNAL_STORAGE-from-org.mozilla.fennec_fdroid \
	
