.DEFAULT_GOAL = clean

.DELETE_ON_ERROR:

package = org.thoughtcrime.securesms

.PHONY: clean
clean: \
	clean-cache \
	;

work_dir = var/cache/signal
.PHONY: clean-cache
clean-cache: ; rm -rf $(work_dir)

$(work_dir)/$(package).apk: $(work_dir)/$(package).url
	cat $<
	curl -sSf -o $@ "$$(cat $<)"

$(work_dir)/$(package).url: $(work_dir)/latest.json
	sed -n -e 's/^.*\(https:\/\/updates\.signal\.org\/android\/Signal-website-universal-release-[1-9][0-9]*.[1-9][0-9]*.[1-9][0-9]*\.apk\).*$$/\1/p' < $< >$@

$(work_dir)/latest.json:
	curl -sSf https://updates.signal.org/android/latest.json -o $@ --create-dirs
