.DEFAULT_GOAL = clean

.DELETE_ON_ERROR:

package = org.thoughtcrime.securesms

.PHONY: clean
clean: \
	clean-cache \
	;

work_dir = var/cache/signal
.PHONY: clean-cache
clean-cache: ; rm -rf $(work_dir)

# From https://www.signal.org/blog/phone-number-privacy-usernames/
# > We’re also introducing a setting that lets you control who can
# > find you by your phone number on Signal. Up until today, anyone
# > who had your phone number ... could look you up on Signal by phone
# > number and message you. You can now restrict this by going to
# > Settings > Privacy > Phone Number > Who can find me by my number
# > and setting it to “Nobody.”
$(work_dir)/$(package).apk: $(work_dir)/$(package).url
	cat $<
	curl -sSf -o $@ "$$(cat $<)"

$(work_dir)/$(package).url: $(work_dir)/latest.json
	sed -n -e 's/^.*\(https:\/\/updates\.signal\.org\/android\/Signal-Android-website-prod-universal-release-[1-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*\.apk\).*$$/\1/p' < $< >$@

$(work_dir)/latest.json:
	curl -sSf https://updates.signal.org/android/latest.json -o $@ --create-dirs
