.DEFAULT_GOAL = clean

.DELETE_ON_ERROR:

package = ch.protonmail.android

.PHONY: clean
clean: \
	clean-cache \
	;

work_dir = var/cache/protonmail
.PHONY: clean-cache
clean-cache: ; rm -rf $(work_dir)

# See also https://proton.me/download/calendar/android/ProtonCalendar-Android.apk
apk_url = https://github.com/ProtonMail/android-mail/releases/download/v7.6.1/ProtonMail-7.6.1_15868.apk

get = curl -sSf -o $(3) --create-dirs $(2) $(1)

$(work_dir)/$(package).apk: ; $(call get,$(apk_url),,$@)

.PHONY: $(work_dir)/$(package).apk-if-modified
$(work_dir)/$(package).apk-if-modified: %-if-modified:
	$(call get,$(apk_url),-z $*,$*)
