non_revocable_dangerous_permissions_from_qualcomm_packages = \
	android.permission.CALL_PHONE-from-com.qti.confuridialer \
	android.permission.PROCESS_OUTGOING_CALLS-from-com.qti.confuridialer \
	android.permission.READ_CALL_LOG-from-com.qti.confuridialer \
	android.permission.READ_CONTACTS-from-com.qti.confuridialer \
	android.permission.READ_PHONE_STATE-from-com.qti.confuridialer \
	android.permission.READ_PHONE_STATE-from-com.qti.dpmserviceapp \
	android.permission.READ_PHONE_STATE-from-com.qti.qualcomm.datastatusnotification \
	android.permission.READ_PHONE_STATE-from-com.qti.xdivert \
	android.permission.ACCESS_COARSE_LOCATION-from-com.qualcomm.location \
	android.permission.ACCESS_FINE_LOCATION-from-com.qualcomm.location \
	android.permission.PROCESS_OUTGOING_CALLS-from-com.qualcomm.location \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.location \
	android.permission.RECEIVE_SMS-from-com.qualcomm.location \
	android.permission.RECEIVE_WAP_PUSH-from-com.qualcomm.location \
	android.permission.ACCESS_FINE_LOCATION-from-com.qualcomm.location.XT \
	android.permission.READ_EXTERNAL_STORAGE-from-com.qualcomm.qti.ims \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.ims \
	android.permission.ACCESS_COARSE_LOCATION-from-com.qualcomm.qti.qdma \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.qdma \
	android.permission.ACCESS_COARSE_LOCATION-from-com.qualcomm.qti.qmmi \
	android.permission.ACCESS_FINE_LOCATION-from-com.qualcomm.qti.qmmi \
	android.permission.CAMERA-from-com.qualcomm.qti.qmmi \
	android.permission.READ_EXTERNAL_STORAGE-from-com.qualcomm.qti.qmmi \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.qmmi \
	android.permission.RECORD_AUDIO-from-com.qualcomm.qti.qmmi \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.qualcomm.qti.qmmi \
	android.permission.CALL_PHONE-from-com.qualcomm.qti.roamingsettings \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.roamingsettings \
	android.permission.CAMERA-from-com.qualcomm.qti.seccamservice \
	android.permission.READ_EXTERNAL_STORAGE-from-com.qualcomm.qti.seccamservice \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.qualcomm.qti.seccamservice \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.seemp.service \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.qti.services.secureui \
	android.permission.GET_ACCOUNTS-from-com.qualcomm.simcontacts \
	android.permission.READ_CONTACTS-from-com.qualcomm.simcontacts \
	android.permission.READ_PHONE_STATE-from-com.qualcomm.simcontacts \
	android.permission.WRITE_CONTACTS-from-com.qualcomm.simcontacts \
	android.permission.ACCESS_COARSE_LOCATION-from-com.quicinc.cne.CNEService \
	android.permission.ACCESS_FINE_LOCATION-from-com.quicinc.cne.CNEService \
	android.permission.READ_PHONE_STATE-from-com.quicinc.cne.CNEService
