extra_non_revocable_dangerous_permissions_from_packages = \
	android.permission.ACCESS_COARSE_LOCATION-from-com.hmdglobal.app.activation \
	android.permission.ACCESS_FINE_LOCATION-from-com.hmdglobal.app.activation \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.activation \
	android.permission.ACCESS_MEDIA_LOCATION-from-com.hmdglobal.app.cdfinger \
	android.permission.READ_EXTERNAL_STORAGE-from-com.hmdglobal.app.cdfinger \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.hmdglobal.app.cdfinger \
	android.permission.PROCESS_OUTGOING_CALLS-from-com.hmdglobal.app.customizationclient \
	android.permission.READ_EXTERNAL_STORAGE-from-com.hmdglobal.app.customizationclient \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.customizationclient \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.hmdglobal.app.customizationclient \
	android.permission.READ_EXTERNAL_STORAGE-from-com.hmdglobal.app.fmradio \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.fmradio \
	android.permission.RECORD_AUDIO-from-com.hmdglobal.app.fmradio \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.hmdglobal.app.fmradio \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.midfm \
	android.permission.ACCESS_COARSE_LOCATION-from-com.hmdglobal.app.midtest \
	android.permission.ACCESS_FINE_LOCATION-from-com.hmdglobal.app.midtest \
	android.permission.READ_EXTERNAL_STORAGE-from-com.hmdglobal.app.midtest \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.midtest \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.hmdglobal.app.midtest \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.myphonehelper \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.omacp \
	android.permission.RECEIVE_WAP_PUSH-from-com.hmdglobal.app.omacp \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.sarauth \
	android.permission.GET_ACCOUNTS-from-com.hmdglobal.app.setupwizardext \
	android.permission.READ_PHONE_STATE-from-com.hmdglobal.app.setupwizardext \
	android.permission.ACCESS_MEDIA_LOCATION-from-com.wos.face.service \
	android.permission.CAMERA-from-com.wos.face.service \
	android.permission.READ_EXTERNAL_STORAGE-from-com.wos.face.service \
	android.permission.RECORD_AUDIO-from-com.wos.face.service \
	android.permission.WRITE_EXTERNAL_STORAGE-from-com.wos.face.service \
	
