#!/bin/sh

REQ_PERMS="requested permissions"
SEP=":"
PERM="[^[:space:]${SEP:?}][^[:space:]${SEP:?}]*"
RESTRICTED_SUFFIX="${SEP:?} restricted=true"

# References:
# - Hint on usage of `adb shell dumpsys package packagename` for
#   insight on permissions for some packages:
#   https://stackoverflow.com/questions/21091022/listing-permissions-of-android-application-via-adb
dump_pkg_info() {
    # Requires android.permission.DUMP for package com.android.shell
    adb shell dumpsys package "${1:?}"
}

keep_from_requested_perms() {
    sed -n -e '/'"${REQ_PERMS:?}"':$/,$p'
}

keep_only_non_empty_lines() {
    grep '[^[:space:]]'
}

keep_only_until_so_indented() {
    sed \
	-n \
	-e '/^'"${1:?}"'[^[:space:]]/p' \
	-e '/^'"${1:?}"'[^[:space:]]/!q'
}

indentation() {
    sed 's/^\([[:space:]]*\)[^[:space:]].*$/\1/'
}

perm() {
    sed \
        -n \
        -e 's/^[[:space:]]*\('"${PERM:?}"'\)$/\1/p' \
        -e 's/^[[:space:]]*\('"${PERM:?}"'\)'"${RESTRICTED_SUFFIX:?}"'$/\1/p'
}

first_line() {
    head -n 1
}

rest_lines() {
    tail -n +2
}

n_lines() {
    wc -l
}

n_bytes() {
    wc -c
}

P="${1:?}"

Dump="$(dump_pkg_info "${P:?}")" || exit 1

{ test 1 -eq $(echo "${Dump:?}" | grep -cF " Package [${P:?}]"); } \
    || exit 1  # Assumption: Exactly one package per dump.

RelevantTail="$(echo "${Dump:?}" \
                     | keep_from_requested_perms \
                     | keep_only_non_empty_lines)"
{ test ! -z "${RelevantTail?}"; } \
    || exit 0  # Assumption: Requested permissions may be not present - not even the title.

ReqPermsTitleLine="$(echo "${RelevantTail:?}" \
                          | first_line)"
{ echo "${ReqPermsTitleLine}" \
      | grep -q '^[[:space:]]*'"${REQ_PERMS:?}"; } \
    || exit 1
PostReqPermsTitle="$(echo "${RelevantTail:?}" \
                          | rest_lines)"
{ test 0 -lt $(echo "${PostReqPermsTitle:?}" \
                   | n_lines); } \
    || exit 0  # Assumption: There may be no requested permissions.
ReqPermsTitleIndent="$(echo "${ReqPermsTitleLine:?}" \
                            | indentation)"
ReqPermsTitleIndentLength=$(echo "${ReqPermsTitleIndent:?}" \
                                | n_bytes)

PostReqPermsTitleIndent="$(echo "${PostReqPermsTitle:?}" \
                                | first_line \
                                | indentation)"
PostReqPermsTitleIndentLength=$(echo "${PostReqPermsTitleIndent:?}" \
                                    | n_bytes)
{ test ${ReqPermsTitleIndentLength:?} \
       -lt ${PostReqPermsTitleIndentLength:?}; } \
    || exit 0  # Assumption: no tabs counting as multiple spaces. # Assumption: There may be no requested permissions.

ReqPermsRaw="$(echo "${PostReqPermsTitle:?}" \
                    | keep_only_until_so_indented "${PostReqPermsTitleIndent:?}")"
ReqPerms="$(echo "${ReqPermsRaw:?}" \
                 | perm)"
{ test $(echo "${ReqPermsRaw:?}" | n_lines) \
       -eq \
       $(echo "${ReqPerms:?}" | n_lines); } \
    || exit 1
echo "${ReqPerms:?}"
