#!/bin/sh

# References:
# - Hint on usage of `adb shell dumpsys package packagename` for
#   insight on permissions for some packages: -
#   https://stackoverflow.com/questions/21091022/listing-permissions-of-android-application-via-adb

P="${1:?}"

adb shell dumpsys package "${1:?}"
exit 0
ReqPermsAndRest="$(adb shell dumpsys package "${1:?}" | sed -n -e '/requested permissions:/,$p')" \
    && ReqPermsIndent=$(echo "${ReqPermsAndRest:?}" | head -n 1 | sed 's/^\([[:space:]]*\)[^[:space:]].*$/\1/') \
    && (echo "${ReqPermsAndRest:?}" | tail -n +2 | grep -v '^[[:space:]]*$' | sed -n -e '/^'"${ReqPermsIndent:?}"'[[:space:]]/P' -e '1,$d')
